--- 
artifacts: 
  type: zip
  files: 
    - "**/*"
  name: "$Env:TEST_ENV_VARIABLE_$(date +%Y-%m-%d).zip"
env: 
  variables: 
    CONFIGURATION: Release
    SOLUTION_NAME: AWSServerlessCheckingOut
    SiteBucketName: testsudhir1
    TEST_ENV_VARIABLE: AWSServerlessCheckingOut_metadata_Api
    WEB_PROJECT_NAME: AWSServerlessCheckingOut
phases: 
  build: 
    commands: 
      - "dotnet build --no-restore AWSServerlessCheckingOut.sln --configuration Release"
  install: 
    runtime-versions: 
      dotnet: 3.1
  pre_build: 
    commands: 
      - "echo \"Region = ${AWS_REGION}\""
      - "echo \"CODEBUILD_SOURCE_REPO_URL = ${CODEBUILD_SOURCE_REPO_URL}\""
      - "echo \"CODEBUILD_RESOLVED_SOURCE_VERSION = ${CODEBUILD_RESOLVED_SOURCE_VERSION}\""
      - "echo \"Account Id = $(echo $CODEBUILD_BUILD_ARN | cut -f5 -d ':')\""
      - "echo \"Repo Name = $(echo $CODEBUILD_SOURCE_VERSION | cut -f2 -d '/')\""
      - "echo \"CONFIGURATION = $(echo ${env:CONFIGURATION})\""
      - "echo \"Commit Id = ${CODEBUILD_RESOLVED_SOURCE_VERSION}\""
      - "echo Restore started on `date`"
      - "export PATH=\"$PATH:/root/.dotnet/tools\""
      - "apt-get update"
      - "apt-get install zip -y"
      - "dotnet restore AWSServerlessCheckingOut.sln"
      - "aws s3 cp --recursive --acl public-read . s3://${SiteBucketName}/"
      - "aws cloudformation deploy --template AWSServerlessCheckingOut/serverless.template --stack-name AWSServerlessCheckingOut --capabilities CAPABILITY_NAMED_IAM"
version: 0.2
