--- 
env: 
  variables: 
    CONFIGURATION: Release
    SOLUTION_NAME: AWSServerlessCheckingOut
    SiteBucketName: testsudhir1
    TEST_ENV_VARIABLE: AWSServerlessCheckingOut_metadata_Api
    WEB_PROJECT_NAME: AWSServerlessCheckingOut
phases: 
  build: 
    commands: 
      - "dotnet build --no-restore AWSServerlessCheckingOut.sln --configuration Release"
      - "dotnet test -c Release --logger trx --results-directory ./testresults"
  install: 
    runtime-versions: 
      dotnet: 3.1
  pre_build: 
    commands: 
      - "echo \"Region = ${AWS_REGION}\""
      - "echo \"CODEBUILD_SOURCE_REPO_URL = ${CODEBUILD_SOURCE_REPO_URL}\""
      - "echo \"CODEBUILD_RESOLVED_SOURCE_VERSION = ${CODEBUILD_RESOLVED_SOURCE_VERSION}\""
      - "echo \"Account Id = $(echo $CODEBUILD_BUILD_ARN | cut -f5 -d ':')\""
      - "echo \"Repo Name = $(echo $CODEBUILD_SOURCE_VERSION | cut -f2 -d '/')\""
      - "echo \"CONFIGURATION = $(echo ${env:CONFIGURATION})\""
      - "echo \"Commit Id = ${CODEBUILD_RESOLVED_SOURCE_VERSION}\""
      - "echo Restore started on `date`"
      - "export PATH=\"$PATH:/root/.dotnet/tools\""
      - "apt-get update"
      - "apt-get install zip -y"
      - "dotnet restore AWSServerlessCheckingOut.sln"
    post_build: 
      commands: 
        - "echo Publish started on `date`"
        - "dotnet publish -c Release -o ./build_output AWSServerlessCheckingOut.sln --self-contained false"
        - "aws s3 cp --recursive --acl public-read . s3://${SiteBucketName}/"
        - "aws cloudformation package --s3-bucket testsudhir1 --template AWSServerlessCheckingOut/aws-lambda-tools-defaults.json --output json > packaged-template.json"
version: 0.2
