--- 
artifacts: 
  files: 
    - "**/*"
phases: 
  build: 
    commands: 
      - "dotnet build AWSServerlessCheckingOut/AWSServerlessCheckingOut/AWSServerlessCheckingOut.csproj"
      - "CD AWSServerlessCheckingOut/AWSServerlessCheckingOut"
      - "dotnet lambda deploy-serverless "  
  install: 
    runtime-versions: 
      dotnet: 3.1
  pre_build: 
    commands: 
      - "echo Restore started on `date`"
      - "dotnet restore AWSServerlessCheckingOut/AWSServerlessCheckingOut/AWSServerlessCheckingOut.csproj"
version: 0.2
