--- 
artifacts: 
  base-directory: ./build_output
  discard-paths: false
  files: 
    - "**/*"
env: 
  variables: 
    DOTNET_CORE_RUNTIME: 3.1
    PROJECT: AWSServerlessCheckingOut
phases: 
  build: 
    commands: 
      - "echo Publish Started on `date`"
      - "dotnet build --no-restore AWSServerlessCheckingOut.sln --configuration Release"
      - "cp Procfile ./build_output"
  install: 
    runtime-versions: 
      dotnet: "${DOTNET_CORE_RUNTIME}"
  pre_build: 
    commands: 
      - "echo \"Region = ${AWS_REGION}\""
      - "echo \"CODEBUILD_SOURCE_REPO_URL = ${CODEBUILD_SOURCE_REPO_URL}\""
      - "echo \"CODEBUILD_RESOLVED_SOURCE_VERSION = ${CODEBUILD_RESOLVED_SOURCE_VERSION}\""
      - "echo \"Account Id = $(echo $CODEBUILD_BUILD_ARN | cut -f5 -d ':')\""
      - "echo \"Repo Name = $(echo $CODEBUILD_SOURCE_VERSION | cut -f2 -d '/')\""
      - "echo \"CONFIGURATION = $(echo ${env:CONFIGURATION})\""
      - "echo \"Commit Id = ${CODEBUILD_RESOLVED_SOURCE_VERSION}\""
      - "echo Restore started on `date`"
      - "dotnet restore AWSServerlessCheckingOut.sln"
reports: 
  $(PROJECT): 
    base-directory: ./restresults
    file-format: VIsualStudioTrx
    files: 
      - "**/*"
version: 0.2
