--- 
phases: 
  build: 
    commands: 
      - "dotnet build -c Release ./AWSServerlessCheckingOut/AWSServerlessCheckingOut.csproj"
  install: 
    runtime-versions: 
      dotnet: 3.1
  pre_build: 
    commands: 
      - "echo Restore started on `date`"
      - "dotnet restore AWSServerlessCheckingOut.csproj"
reports: 
  DotnetTestExamples: 
    base-directory: ./testresults
    file-format: VisualStudioTrx
    files: 
      - "**/*"
version: 0.2
